### PR TITLE
added response return for files uploading

### PR DESCRIPTION
**Pull request by PavelZagalsky-Via**
I need the response details for the files uploading for further processing.
Is it possible to implement it?
Thanks!

### CODE REVIEW

**Comment by szprutamich** [comment]
Uploading files directly to projects is already deprecated.

**Comment by PavelZagalsky-Via** [comment]
What is the proper way to upload the App file and the Test file?

**Comment by szprutamich** [comment]
Upload files to "Files library" - http://docs.bitbar.com/testing/api/files/index.html#uploading-file
Running tests with json config: http://docs.bitbar.com/testing/api/tests/index.html

**Comment by PavelZagalsky-Via** [comment]
Is there a way to do these calls with Python as well?

**Comment by szprutamich** [comment]
uploading files (def upload_file(self, filename)): https://github.com/bitbar/testdroid-api-client-python/blob/master/testdroid/__init__.py#L403
running tests (def start_test_run_using_config(self, test_run_config={})): https://github.com/bitbar/testdroid-api-client-python/blob/master/testdroid/__init__.py#L480

**Comment by szprutamich** [comment]
This change is already merged, closing

**Pull request closed without merging**
